version: "3.7"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:5.0.4"
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_URL=redis://redis:6379
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

  fastapi:
    build: .
    command: bash -c "poetry run uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/todo
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
      - web-db
    volumes:
      - ./todo:/todo/todo

  worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    volumes:
      - ./todo:/todo/todo
    command: "poetry run celery -A core.celery_worker worker -B -l info -Q test-queue -c 1"

  web-db:
    image: postgres:13-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    volumes:
        - "./postgres-data:/var/lib/postgresql/data"
    restart: always


  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fastapi
    command: ["nginx-debug", "-g", "daemon off;"]

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local